theme="polymer"
baseURL = 'http://topblog.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
MetaDataFormat = "toml"
paginate = 10 # optional
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Copyright Text"

[params]
  author = "Your Name"
  photo = "images/photo.png" # optional
  profile = "images/profile.png" # optional
  cover = "images/cover.png" # optional
  twitter = "Your Twitter Name" # optional
  github = "Your Github Name" # optional
  facebook = "Your facebook Name" # optional
  gplus = "Your Google+ Name" # optional
  linkedin = "Your linkedin Name" # optional
  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:filename/" # optional